### ISSUE TITLE
Date filter in Add Registration in Admin 

### ISSUE THREAD

**Issue by haggyshan** [timberline-secondary/flex-site#84]
Add a date filter in the registration section for registering a student.  Right now the drop down list lists ALL the event and you cannot tell by looking at it which event (date) the student will actually be registered for.

**Comment by tylerecouture** [comment]
Registrations shouldn't be created in the admin as it won't do any checks for conflicting events or check max_capacity, and many of the other logic that goes in to a registration.  I'll think about a way for teachers to add students on the front of the site.

Is there a reason why teachers need to add students to events?  Perhaps there is a different underlying problem that could be addressed?

**Comment by haggyshan** [comment]
Well,
with the cutoffs, if they show up for an event that they can't register for (or thought they had but didn't) instead of making a list that Cindy has to go through to remove them from the callout, teachers would like to be able to add them, Bev at the front office sometime has to add the students who aren't there for a block.
shan


Shannon Hagen

Media Educator

Timberline Secondary

shannon.hagen@sd72.bc.ca<mailto:shannon.hagen@sd72.bc.ca>

250-923-9500  ext. 2530

________________________________

**Comment by tylerecouture** [comment]
Ok, so what do you think of this:

If students can show up late to an event that allows for this, then,
ideally, they should still be able to still register themselves rather than
have a teacher do it.

If teachers signing up students is just a work around because students
can't do it themselves right now, then it would make more sense to fix that
problem rather than waste time on a work around.

Yesterday I got the cutoff times working again (if you go edit or create an
event you will see it there, and I'm pretty sure it's working properly :)

It would be very easy to allow for negative cut off times, so if the
library/humanities commons allows for students to register up to 30 minutes
after the start of the event, then we should build that directly in to the
event.

It might be good to have one catch-all event like this announced to all
teachers, so that when student come complaining about forgetting or not
having an event, they can be sent to the catch-all.

If a teacher doesn't mind late walk-ins for their own event, then they can
allow that in the event settings, and get the late students to register
themselves. (Personally, I kick everyone out who isn't registered, because
once word spreads that they don't have to register on time, the incentive
is lost and we lose one of our accountability mechanisms)

What do you think?

**Comment by haggyshan** [comment]
Sounds good.  What do you mean by a catch all event?
shan


Shannon Hagen

Media Educator

Timberline Secondary

shannon.hagen@sd72.bc.ca<mailto:shannon.hagen@sd72.bc.ca>

250-923-9500  ext. 2530

________________________________

**Comment by tylerecouture** [comment]
By catch-all I mean, where should teachers tell students to go if they
haven't signed up for anything?

**Comment by haggyshan** [comment]
Okay
shan


Shannon Hagen

Media Educator

Timberline Secondary

shannon.hagen@sd72.bc.ca<mailto:shannon.hagen@sd72.bc.ca>

250-923-9500  ext. 2530

________________________________
